renamed sample program to from helloserver to podtatoserver
cncf/podtato-head pull request #34
Opened 2021-03-01 18:55 UTC by AloisReitbauer

These are the first changes to update the sample

2021-03-01 20:56 UTC, thschue approved these changes
lgtm

2021-03-02 09:41 UTC, jetzlstorfer requested changes
found one occurrence of old name which should be changed

2021-03-02 09:41 UTC, jetzlstorfer commented on delivery/CNABwithPorter/porter.yaml
>  description: "A porter file for the hello server"
should be renamed to "podtato server"?

2021-03-02 13:18 UTC, merged

2021-03-02 13:19 UTC, yogeek commented
In `delivery/manifest/manifest.yaml` you missed the names of the resources I think