Ketch
cncf/podtato-head pull request #57
Opened 2021-04-15 15:58 UTC by vfarcic

Adding Ketch

2021-04-19 13:37 UTC, AloisReitbauer commented
This example is not using the podtato demo app and runs the individual use cases you can find the steps [here](https://github.com/cncf/podtato-head/blob/main/contributing.md)

2021-04-19 13:38 UTC, AloisReitbauer requested changes

2021-04-19 13:38 UTC, AloisReitbauer commented on delivery/ketch/README.md
> +ketch app deploy bulletinboard -i docker.io/shipasoftware/bulletinboard:1.0
This deploys the wrong application

2021-04-19 14:01 UTC, vfarcic commented
My bad... Let me do it again...

2021-04-26 07:56 UTC, AloisReitbauer commented
Great! Any ETA? I would need to create a tag before moving towards the multi-service version of podtato-head.

2021-04-26 13:34 UTC, vfarcic commented
Sorry for the delay. I'll work on it today and update the PR ASAP.

2021-04-26 17:10 UTC, vfarcic commented
There is a problem that prevents me from using the app and the Dockerfile as-is with Ketch.

Ketch assumes that there is `entrypoint` in Dockerfile or, if there isn't, it "injects" `command: /bin/sh ...` into manifests. Since the final image is based on `scratch`, there is no `sh`.

Do you think it would be possible to modify the Dockerfile and change:

```
CMD ["/podtatoserver", "--version", "0.1.0" ]
```

to 

```
ENTRYPOINT ["/podtatoserver"]

CMD ["--version", "0.1.0" ]
```

That probably shouldn't affect any of the existing instructions.

2021-04-28 19:56 UTC, vfarcic commented
We fixed the issue in Ketch. Now it should work. I'll update the PR before the end of the week.

2021-04-28 21:34 UTC, vfarcic commented
@AloisReitbauer I just updated the PR to use podtato. Can you please take a look and let me know if it's okay or if there is something missing.

2021-05-03 09:49 UTC, AloisReitbauer commented
Hello, trying the example on Kind. Many people have requested they run on kind.

One thing I noticed: 

http://podtato.127.0.0.1.nip.io.shipa.cloud is shown as the URL for the app. I added 127.0.0.1.nip.io as my local domain. I don't think the shipa.cloud part should be there

2021-05-05 14:52 UTC, vfarcic commented
@AloisReitbauer I just updated it to use k3d, mostly because I already had an example with it. Is that OK or you have a strong preference towards kind?

2021-05-10 15:04 UTC, vfarcic commented
How does it look? Is there anything else I can do to improve it?

2021-05-18 11:32 UTC, vfarcic commented
@AloisReitbauer Please let me know if there is anything missing or wrong.

2021-06-07 08:15 UTC, AloisReitbauer commented
Sorry this took so long. Approving and re checking the workflow

2021-06-07 08:16 UTC, merged